ARG ROS_DISTRO=jazzy

FROM osrf/ros:${ROS_DISTRO}-desktop
ARG ROS_DISTRO
ARG USERNAME=arc
ARG USER_PASSWORD=123
ARG USER_UID=1000
ARG USER_GID=$USER_UID

SHELL ["/bin/bash", "-c"]

# Install dependencies
RUN apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
        curl \
        locales \
        nano \
        openssh-server \
        python3 \
        python3-colcon-common-extensions \
        python3-pip \
        python3-rosdep \
        python3-venv \
        software-properties-common \
        sudo && \
    rm -rf /var/lib/apt/lists/*

# Create the user
RUN if getent group ${USER_GID} >/dev/null; then \
        groupmod -n ${USERNAME} $(getent group ${USER_GID} | cut -d: -f1); \
    else \
        groupadd -g ${USER_GID} ${USERNAME}; \
    fi && \
    if getent passwd ${USER_UID} >/dev/null; then \
        usermod -l ${USERNAME} -m -d /home/${USERNAME} $(getent passwd ${USER_UID} | cut -d: -f1); \
    else \
        useradd -m -u ${USER_UID} -g ${USER_GID} -s /bin/bash ${USERNAME}; \
    fi && \
    echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    && echo "${USERNAME}:${USER_PASSWORD}" | chpasswd

# Set the locale
RUN locale-gen en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8

# Set up sshd working directory
RUN mkdir -p /run/sshd && \
    ssh-keygen -A
    # chmod 0755 /var/run/sshd && \

# # SSH hardening for container use
# RUN sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config && \
#     sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
#     sed -i 's|^#\?AuthorizedKeysFile.*|AuthorizedKeysFile .ssh/authorized_keys|' /etc/ssh/sshd_config

RUN sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config && \
    sed -i 's/^#\?ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config || true

# ********************************************************
# * Anything else you want to do like clean up goes here *
# ********************************************************
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /home/$USERNAME/.bashrc \
    && echo "cd /home/$USERNAME/workspace" >> /home/$USERNAME/.bashrc

# Create and own the ROS workspace before switching user
RUN mkdir -p /home/$USERNAME/workspace/src && \
    chown -R ${USERNAME}:${USERNAME} /home/$USERNAME/workspace && \
    chmod -R 0755 /home/$USERNAME/workspace

COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 22
# ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/usr/sbin/sshd", "-D"]